# Generated by Django 4.1.3 on 2022-11-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_item_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='info',
            field=models.TextField(default='description', max_length=2000),
        ),
    ]
